/* RANKING SOJUSZY BEZ WYSWIETLENIA SOJUSZY O ID= NULL */
SELECT "Wynik_Sojuszu","ID_Sojusz","Nazwa_Sojuszu"
FROM "Sojusz"
WHERE "ID_Sojusz" IS NOT NULL
ORDER BY "Wynik_Sojuszu";

/* WYSWIETLENIE KOLUMNY ID GRACZA Z TABELI GRACZ BEZ GRACZA Z ID GRACZA =1 */
SELECT "ID_Gracza"
FROM "Gracz"
WHERE NOT EXISTS
(SELECT "ID_Gracza" FROM "Gracz" WHERE "ID_Gracza"=1);
